---
title: "Group 26 CA pollution burden"
author: "Maddie Frick and Jonah Seif"
date: "11/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(hexbin)
```


```{r}
ces<-read.csv(here("data","ces3demographics.csv")) %>%  #read in the dataset
  clean_names()

```

```{r}
# Create ggplot of %white vs CES3.0
ggplot(data = ces,
       aes(x = white, y = ces_3_0_score))+
  labs(x = "White Percent", y = "CalEnviroScreen pollution burden score",
       title = "White Population Impacts on CalEnviroScreen pollution burden score") +
  geom_hex() +
  scale_fill_gradient(low = "navy", high = "orange")+
  theme_minimal()

```
In general, as the percentage of the population that is white increases, the CES 3.0 score. This score is a combination of pollution burden and population characteristics, which is higher with increased exposures and environmental effects, while taking into account sensitive populations and socioeconomic factors.
